services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - backend_static:/app/static
    expose:
      - "8000"
    ports:
      - 8000:8000
    environment:
      - PG_DATABASE_URL=postgresql+asyncpg://fastapi:fastapi@db:5432/postgres
      - SECRET_KEY=secretsecret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=development
    entrypoint: ["/app/scripts/start-backend.dev.sh"]
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgresql_db
    image: postgres:16-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
    expose:
      - "5432"
    ports:
      - "5435:5432"
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -U postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db: {}
  backend_static: {}