"""fresh start

Revision ID: 73fdd3a2637c
Revises: 
Create Date: 2024-12-12 12:39:20.159735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fdd3a2637c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'communication_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_candidates_uuid', table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index('ix_candidates_uuid', 'candidates', ['uuid'], unique=False)
    op.alter_column('candidates', 'communication_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
